module.exports = {
  User: require('./User'),
  Astrologer: require('./Astrologer'),
  Wallet: require('./Wallet'),
  WalletTransaction: require('./WalletTransaction'),
  ChatRoom: require('./ChatRoom'),
  Message: require('./Message'),
  AIChat: require('./AIChat'),
  Category: require('./Category'),
  Product: require('./Product'),
  Order: require('./Order'),
  Review: require('./Review'),
  Coupon: require('./Coupon'),
  Payment: require('./Payment'),
  Notification: require('./Notification'),
  Banner: require('./Banner'),
  Blog: require('./Blog'),
  Referral: require('./Referral'),
  Withdrawal: require('./Withdrawal'),
  Settings: require('./Settings'),
  Cart: require('./Cart'),
  AuditLog: require('./AuditLog'),
  AIAstrologer: require('./AIAstrologer'),
  Pooja: require('./Pooja'),
  PoojaBooking: require('./PoojaBooking'),
  ContactMessage: require('./ContactMessage'),
};
